services:
  - type: web
    name: backend-mercapp
    env: node
  buildCommand: cd backend && npm install && npm run build
startCommand: cd backend && npm run start

    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
